# Reference guide: https://dzone.com/articles/how-to-dockerize-a-react-app-with-vite
services:
  #contains all container definitions
  frontend:
    build: .
    ports:
      - "5173:5173" #host port on the left, container port on the right
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      # backend:
      # to be added later

      # database:
      # to be added later
